### PR TITLE
DB migration

### PR DESCRIPTION
**Pull request by Tony1023**

### CODE REVIEW

**Comment by Tony1023** [comment]
@cchyung 
Looks like toggling the field is pretty viable https://sequelize.org/master/class/lib/associations/belongs-to-many.js~BelongsToMany.html
Only bad thing about this is that we need to reset/drop the dish_tags table in the database

**Comment by Tony1023** [comment]
@cchyung Two fields added into db for future reference

**Comment by Tony1023** [comment]
This should be the command to execute the migration. I think it needs to be run before we push the new version on this branch to Heroku
```bash
$ heroku run sequelize db:migrate --env production
```

**Comment by cchyung** [comment]
Let's hold off on merging this so we can test with production first

**Comment by Tony1023** [comment]
> Looks good

LGTM is the correct phrase XD

**Comment by Tony1023** [comment]
@cchyung  Things are working fine on the staging backend so I'm merging this branch

**Pull request merged**
